### ISSUE TITLE
Bio writing prompt is misleading when viewing others' profiles

### ISSUE THREAD

**Issue by davwheat** [FriendsOfFlarum/user-bio#28]
I'm a nitpicker! If you look at another user's profile with permissions to edit their bio, it still says 'write something about yourself'.

![image](https://user-images.githubusercontent.com/7406822/109702785-9af02780-7b8c-11eb-9d40-b57017dd685e.png)

**Comment by askvortsov1** [comment]
This is actually a feature: essentially, when the current admin of a site leaves, all moderators rush to write something about themselves in the bios of all users without bios. Whoever has the most wins the role of new admin. If this is changed, it will break a crucial workflow.

**Comment by davwheat** [comment]
Bahahahahahahaha!

How about an automated check to see if there are any users of the Admin group?

_(I edited nothing...)_

**Comment by askvortsov1** [comment]
Keep in mind some forums might use arbitrary groups as the "forum owner" group: what if there are multiple admins? However, I think adding a UI to select the "forum owner" group to the admin dashboard would be clunky. I think we need a pre-trained classifier that will be fed all posts made on the forum, and based on that, classify groups as "owner" or "non-owner"

May I recommend ResNet 50?

**Comment by davwheat** [comment]
At this point, this might be better off in a different extension, one with an automated bio tracker and integrated scoreboard, perhaps?
