### ISSUE TITLE
Banned user should be unable to edit bio

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/user-bio#3]
A banned user should be not able to edit user bio.
This can be the place where spammers put links or not good material.

**Comment by Ralkage** [comment]
@PeopleInside is this still an issue?

**Comment by PeopleInside** [comment]
I think yes. Is a suggestion. A banned user should be not able to edit his bio.

**Comment by Ralkage** [comment]
I agree with you, they can easily leave explicit messages to either flame or detour members and staff.

We'll look into this issue/suggestion and get back to you :)

@luceos or @datitisev, thoughts?

**Comment by luceos** [comment]
Absolutely need to tackle this.
