### ISSUE TITLE
Save and event gets triggered for changing null to empty string

### ISSUE THREAD

**Issue by clarkwinkelmann** [FriendsOfFlarum/user-bio#38]
## Bug Report

**Current Behavior**
After a new user signs up, clicking on the bio and then clicking outside triggers a save and dispatches the event despite no change taking place

**Steps to Reproduce**
1. Create new user
2. Visit user profile
3. Start editing bio
4. Don't type anything, exit field

**Expected Behavior**
The bio was blank and is still blank, no API request is needed and no event should be dispatched.

**Screenshots**

**Environment**
- Flarum version: 1.1

Observed on Flarum Discuss.

**Possible solution(s)**

The check for change in the frontend should probably assume `null` and `''` are the same value. Currently it's not.

https://github.com/FriendsOfFlarum/user-bio/blob/7fa81d5c2d98dd3acbaf162d0e0a01535f09ca70/js/src/forum/components/UserBio.js#L118

**Additional Context**
When the extension is used on its own this causes absolutely no problem. But when my Audit Log extension is used, this "edit" is logged because the event is dispatched.

Maybe some change should also be done in the backend to stop dispatching the event when the bio hasn't actually changed. Right now repeatedly saving the same value via the REST API will also result in the event being sent multiple times.

**Comment by ashwin47** [comment]
Encountered the same issue.
