### ISSUE TITLE
Bio gets completely deleted if admin clicks on the bio of others.

### ISSUE THREAD

**Issue by therealmaxmoon** [FriendsOfFlarum/user-bio#50]
## Bug Report

**Current Behavior**

An existing bio of another user than the admin itself gets deleted if the admin clicks on it.

A bio can accidentally be deleted, if you only want to edit one word.

The bio gets deleted, too, if you want to check a link in the bio. (Admins should be able to follow links to check if it's legal/acceptable). The link will open, but going back to the profile, the bio was deleted at the same time. (only middle mouse works without deleting anything).

**Steps to Reproduce**

1. Go to a user, who has filled out the bio field
2. Click into the bio field
3. Bio will be deleted

**Expected Behavior**
It should be possible to edit an existing bio to e.g. remove bad words, instead of insta-delete.

**Environment**

- Flarum version: 1.8.1
- Extension version: 1.2.0
- Hosting environment: free flarum
- PHP version: 8.2.4
- Browser: Firefox

**Comment by wowaTYPO3** [comment]
I can confirm this problem in the latest version.
